{name: 'All Elementary Grades'},
{name: 'Pre-School'},
{name: 'Kindergarten'},
{name: '1st Grade'},
{name: '2nd Grade'},
{name: '3rd Grade'},
{name: '4th Grade'},
{name: '5th Grade'},
{name: '6th Grade'},
{name: '7th Grade'},
{name: '8th Grade'},
{name: '9th Grade'},
{name: '10th Grade'},
{name: '11th Grade'},
{name: '12th Grade'},
{name: 'Higher than 12th Grade'}
