{name: "Alabama A&M University"},
{name: "Alabama Alternative Route"},
{name: "Alabama State University"},
{name: "Athens State University"},
{name: "Auburn University"},
{name: "Auburn University - Montgomery"},
{name: "Birmingham-Southern College"},
{name: "Concordia College"},
{name: "Faulkner University"},
{name: "Huntingdon College"},
{name: "Jacksonville State University"},
{name: "Judson College"},
{name: "Miles College"},
{name: "Oakwood University"},
{name: "Samford University"},
{name: "Spring Hill College"},
{name: "Stillman College"},
{name: "Talladega College"},
{name: "Troy University"},
{name: "Tuskegee University"},
{name: "University of Alabama"},
{name: "University of Alabama at Birmingham"},
{name: "University of Alabama in Huntsville"},
{name: "University of Mobile"},
{name: "University of Montevallo"},
{name: "University of North Alabama"},
{name: "University of South Alabama"},
{name: "University of West Alabama"},
{name: "Alaska Pacific University"},
{name: "University of Alaska Anchorage"},
{name: "University of Alaska Fairbanks"},
{name: "University of Alaska Southeast"},
{name: "American Samoa Community College"},
{name: "University of Hawaii-Manoa: American Samoa cohort"},
{name: "American Board for Certification of Teacher Excellence - AZ"},
{name: "Arizona Christian University"},
{name: "Arizona State University - Mary Lou Fulton Teachers College"},
{name: "Arizona Teaching Fellows--TNTP"},
{name: "Grand Canyon University"},
{name: "Northern Arizona University"},
{name: "Northern Arizona University - Yuma"},
{name: "Ottawa University"},
{name: "Pima Community College"},
{name: "Prescott College"},
{name: "Rio Salado College"},
{name: "Rio Salado/North Central University"},
{name: "Scottsdale Community College"},
{name: "TEACH-NOW - AZ"},
{name: "University of Arizona"},
{name: "University of Arizona South"},
{name: "University of Phoenix - AZ"},
{name: "Arkansas Department of Education - Arkansas Professional Pathway to Educator Licensure"},
{name: "Arkansas State University"},
{name: "Arkansas Teacher Corps"},
{name: "Arkansas Tech University"},
{name: "Central Baptist College"},
{name: "Crowley's Ridge College"},
{name: "Harding University"},
{name: "Henderson State University"},
{name: "Hendrix College"},
{name: "John Brown University"},
{name: "Lyon College"},
{name: "Ouachita Baptist University"},
{name: "Philander Smith College"},
{name: "Southern Arkansas University"},
{name: "Teach for America - AR"},
{name: "University of Arkansas - Fayetteville"},
{name: "University of Arkansas - Fort Smith"},
{name: "University of Arkansas - Little Rock"},
{name: "University of Arkansas - Monticello"},
{name: "University of Arkansas - Pine Bluff"},
{name: "University of Central Arkansas"},
{name: "University of the Ozarks"},
{name: "Williams Baptist College"},
{name: "Academy of Art University"},
{name: "Alliant International University"},
{name: "Antioch University - CA"},
{name: "Argosy University"},
{name: "Azusa Pacific University"},
{name: "Bard College"},
{name: "Bay Area School of Enterprise (REACH Institute)"},
{name: "Biola University"},
{name: "Brandman University"},
{name: "California Baptist University"},
{name: "California Lutheran University"},
{name: "California Polytechnic State University, San Luis Obispo"},
{name: "California State Polytechnic University, Pomona"},
{name: "California State University, Bakersfield"},
{name: "California State University, Channel Islands"},
{name: "California State University, Chico"},
{name: "California State University, Dominguez Hills"},
{name: "California State University, East Bay"},
{name: "California State University, Fresno"},
{name: "California State University, Fullerton"},
{name: "California State University, Long Beach"},
{name: "Cal State LA"},
{name: "California State University, Monterey Bay"},
{name: "California State University, Northridge"},
{name: "California State University, Sacramento"},
{name: "California State University, San Bernardino"},
{name: "California State University, San Marcos"},
{name: "California State University, Stanislaus"},
{name: "Cal State TEACH"},
{name: "Chapman University"},
{name: "Claremont Graduate University"},
{name: "Concordia University"},
{name: "Dominican University of California"},
{name: "Fresno Pacific University"},
{name: "Hebrew Union College"},
{name: "High Tech High Communities"},
{name: "Holy Names University"},
{name: "Hope International University"},
{name: "Humboldt State University"},
{name: "Humphreys College"},
{name: "La Sierra University"},
{name: "Los Angeles County Office of Education"},
{name: "Los Angeles Unified School District"},
{name: "Loyola Marymount University"},
{name: "Mills College"},
{name: "Mount St. Mary’s University - CA"},
{name: "Mt. Diablo Unified School District"},
{name: "National University"},
{name: "Notre Dame de Namur University"},
{name: "Pacific Oaks College"},
{name: "Pacific Union College"},
{name: "Patten University"},
{name: "Pepperdine University"},
{name: "Point Loma Nazarene University"},
{name: "San Diego Christian College"},
{name: "San Diego City Unified School District"},
{name: "San Diego State University"},
{name: "San Francisco State University"},
{name: "San Joaquin County Office of Education - Project IMPACT"},
{name: "San Jose State University"},
{name: "Santa Clara University"},
{name: "Simpson University"},
{name: "Sonoma State University"},
{name: "St. Mary's College of California"},
{name: "Stanford University"},
{name: "Stanislaus County Office of Education"},
{name: "Teacher's College of San Joaquin"},
{name: "The Master’s University"},
{name: "Touro University"},
{name: "Tulare County Office of Education"},
{name: "United States University"},
{name: "University of California, Berkeley"},
{name: "University of California, Davis"},
{name: "University of California, Irvine"},
{name: "University of California, Los Angeles"},
{name: "University of California, Riverside"},
{name: "University of California, San Diego"},
{name: "University of California, Santa Barbara"},
{name: "University of California, Santa Cruz"},
{name: "University of LaVerne"},
{name: "University of Phoenix - CA"},
{name: "University of Redlands"},
{name: "University of San Diego"},
{name: "University of San Francisco"},
{name: "University of Southern California"},
{name: "University of the Pacific"},
{name: "Vanguard University"},
{name: "Western Governors University - CA"},
{name: "Westmont College"},
{name: "Whittier College"},
{name: "William Jessup University"},
{name: "Adams State University"},
{name: "Archdiocese of Denver"},
{name: "Boulder Journey School"},
{name: "Centennial Board of Cooperative Education Services - CO"},
{name: "Colorado Christian University"},
{name: "Colorado Mesa University"},
{name: "Colorado State University - Fort Collins"},
{name: "Colorado State University - Pueblo"},
{name: "Colorado State University-Global Campus"},
{name: "Denver Public Schools"},
{name: "Douglas County School District"},
{name: "Eagle Rock School & Professional Development Center"},
{name: "East Central Board of Cooperative Education Services - CO"},
{name: "Fort Lewis College"},
{name: "Friends' School"},
{name: "Metropolitan State University of Denver"},
{name: "Mountain Board of Cooperative Education Services - CO"},
{name: "Northeast Board of Cooperative Education Services - CO"},
{name: "Northwest Board of Cooperative Education Services - CO"},
{name: "Pikes Peak  Board of Cooperative Education Services - CO"},
{name: "Public Education & Business Coalition - CO"},
{name: "Regis University"},
{name: "Rocky Mountain College of Art and Design"},
{name: "San Luis Valley  Board of Cooperative Education Services - CO"},
{name: "Southeastern  Board of Cooperative Education Services - CO"},
{name: "Stanley British Primary School"},
{name: "The Colorado College"},
{name: "University of Colorado - Boulder"},
{name: "University of Colorado - Colorado Springs"},
{name: "University of Colorado - Denver"},
{name: "University of Denver"},
{name: "University of Northern Colorado"},
{name: "University of Phoenix - CO"},
{name: "West Central Licensing Program"},
{name: "Western State Colorado University"},
{name: "Albertus Magnus College"},
{name: "OHE — Alternate Route to Certification"},
{name: "Central Connecticut State Univ"},
{name: "Charter Oak State College ECE ARC"},
{name: "Connecticut College"},
{name: "Eastern Connecticut State University"},
{name: "Fairfield University"},
{name: "Mitchell College"},
{name: "Quinnipiac University"},
{name: "Sacred Heart University"},
{name: "Southern Connecticut State Univ"},
{name: "Teach for America - CT"},
{name: "University of Bridgeport"},
{name: "University of Connecticut"},
{name: "University of Hartford"},
{name: "University of New Haven"},
{name: "University of Saint Joseph"},
{name: "Western Connecticut State University"},
{name: "DE Alternative Routes to Certification"},
{name: "Delaware State University"},
{name: "University of Delaware"},
{name: "Wesley College"},
{name: "Wilmington University"},
{name: "American University"},
{name: "Capitol Teaching Residency"},
{name: "Catholic University of America"},
{name: "Center for Inspired Teaching"},
{name: "Gallaudet University"},
{name: "Howard University"},
{name: "Teach for America - DC"},
{name: "TEACH-NOW - DC"},
{name: "The George Washington University"},
{name: "TNTP Academy - DC"},
{name: "Trinity Washington University"},
{name: "University of the District of Columbia"},
{name: "Urban Teachers - DC"},
{name: "Ave Maria University"},
{name: "Baptist College of Florida"},
{name: "Barry University"},
{name: "Bethune-Cookman University"},
{name: "Broward College"},
{name: "Chipola College"},
{name: "Clearwater Christian College"},
{name: "College of Central Florida"},
{name: "Daytona State College"},
{name: "District Alternative Certification Program"},
{name: "Edward Waters College"},
{name: "Flagler College"},
{name: "Florida A&M University"},
{name: "Florida Atlantic University"},
{name: "Florida College"},
{name: "Florida Gateway College"},
{name: "Florida Gulf Coast University"},
{name: "Florida Institute of Technology"},
{name: "Florida International University"},
{name: "Florida Memorial University"},
{name: "Florida Southern College"},
{name: "Florida Southwestern State College"},
{name: "Florida State College at Jacksonville"},
{name: "Florida State University"},
{name: "Gulf Coast State College"},
{name: "Hillsborough Community College"},
{name: "Indian River State College"},
{name: "Jacksonville University"},
{name: "Keiser University"},
{name: "Lake-Sumter State College"},
{name: "Lynn University"},
{name: "Miami Dade College"},
{name: "Northwest Florida State College"},
{name: "Nova Southeastern University"},
{name: "Palm Beach Atlantic University"},
{name: "Palm Beach State College"},
{name: "Pasco Hernando State College"},
{name: "Pensacola State College"},
{name: "Polk State College"},
{name: "Rollins College"},
{name: "Saint Leo University"},
{name: "Santa Fe College"},
{name: "Seminole State College"},
{name: "Southeastern University - FL"},
{name: "Southern Technical College"},
{name: "St. Johns River State College"},
{name: "St. Petersburg College"},
{name: "State College of Florida, Manatee-Sarasota"},
{name: "Stetson University"},
{name: "Teacher Education University"},
{name: "University of Central Florida"},
{name: "University of Florida"},
{name: "University of Miami"},
{name: "University of North Florida"},
{name: "University of South Florida"},
{name: "University of South Florida - Sarasota Manatee"},
{name: "University of South Florida - St. Petersburg"},
{name: "University of Tampa"},
{name: "University of West Florida"},
{name: "Valencia College"},
{name: "Warner University"},
{name: "Albany State University"},
{name: "Armstrong State University"},
{name: "Augusta University"},
{name: "Berry College"},
{name: "Brenau University"},
{name: "Brewton-Parker College"},
{name: "Central Savannah River Area RESA"},
{name: "Clark Atlanta University"},
{name: "Clayton County Schools"},
{name: "Clayton State University"},
{name: "College of Coastal Georgia"},
{name: "Columbus State University"},
{name: "Covenant College"},
{name: "Dalton State School of Education"},
{name: "Dekalb County Schools"},
{name: "Emmanuel College"},
{name: "First District RESA"},
{name: "Fort Valley State University"},
{name: "Fulton County Schools"},
{name: "Georgia Charter School Association (GCSA)"},
{name: "Georgia College and State University"},
{name: "Georgia Gwinnett College"},
{name: "Georgia Southern University"},
{name: "Georgia Southwestern State University"},
{name: "Georgia State University"},
{name: "Georgia Teaching Fellows"},
{name: "Gordon State College"},
{name: "Griffin RESA"},
{name: "Gwinnett County Schools"},
{name: "Kennesaw State University"},
{name: "Lagrange College"},
{name: "Mercer University"},
{name: "Metropolitan RESA"},
{name: "Middle Georgia RESA"},
{name: "Middle Georgia State University"},
{name: "Northeast Georgia RESA"},
{name: "Northwest Georgia RESA"},
{name: "Oconee RESA"},
{name: "Okefenokee RESA"},
{name: "Paine College"},
{name: "Piedmont College"},
{name: "Pioneer RESA"},
{name: "Point University"},
{name: "Reinhardt University"},
{name: "Shorter University"},
{name: "Southwest Georgia RESA"},
{name: "Spelman College"},
{name: "Teach for America- GA"},
{name: "Technical College System of Georgia"},
{name: "Thomas University"},
{name: "Toccoa Falls College"},
{name: "Truett-McConnell College"},
{name: "University of Georgia"},
{name: "University of North Georgia"},
{name: "University of West Georgia"},
{name: "Valdosta State University"},
{name: "Wesleyan College"},
{name: "West Georgia RESA"},
{name: "Young Harris College"},
{name: "University of Guam"},
{name: "Brigham Young University-Hawaii"},
{name: "Chaminade University"},
{name: "Hawaii Pacific University"},
{name: "iteach Hawaii"},
{name: "Kaho'iwai"},
{name: "Leeward Community College"},
{name: "Teach for America- HI"},
{name: "University of Hawaii Hilo/Kahuawaiola"},
{name: "University of Hawaii-Hilo"},
{name: "University of Hawaii-Manoa"},
{name: "University of Hawaii-West Oahu"},
{name: "University of Phoenix - HI"},
{name: "American Board for Certification of Teacher Excellence- ID"},
{name: "Boise State University"},
{name: "Brigham Young University - Idaho"},
{name: "College of Idaho"},
{name: "Idaho State University"},
{name: "Lewis-Clark State College"},
{name: "Northwest Nazarene University"},
{name: "Teach for America - ID"},
{name: "University of Idaho"},
{name: "Augustana College"},
{name: "Aurora University"},
{name: "Benedictine University"},
{name: "Blackburn College"},
{name: "Bradley University"},
{name: "Chicago State University"},
{name: "Chicago Teaching Fellows/TNTP Academy"},
{name: "Columbia College"},
{name: "Concordia University"},
{name: "DePaul University"},
{name: "Dominican University"},
{name: "Eastern Illinois University"},
{name: "Elmhurst College"},
{name: "Erikson Institute"},
{name: "Eureka College"},
{name: "Governors State University"},
{name: "Greenville College"},
{name: "Hebrew Theological College"},
{name: "Illinois College"},
{name: "Illinois Institute of Technology"},
{name: "Illinois State University"},
{name: "Illinois Wesleyan University"},
{name: "Judson University"},
{name: "Kendall College"},
{name: "Knox College"},
{name: "Lake Forest College"},
{name: "Lewis University"},
{name: "Loyola University of Chicago"},
{name: "MacMurray College"},
{name: "McKendree University"},
{name: "Millikin University"},
{name: "Monmouth College"},
{name: "National-Louis University"},
{name: "North Central College - IL"},
{name: "North Park University"},
{name: "Northeastern Illinois University"},
{name: "Northern Illinois University"},
{name: "Northwestern University"},
{name: "Olivet Nazarene University"},
{name: "Quincy University"},
{name: "Relay Graduate School of Education - IL"},
{name: "Rockford University"},
{name: "Roosevelt University"},
{name: "Saint Xavier University"},
{name: "School of the Art Institute of Chicago"},
{name: "Southern Illinois - Edwardsville"},
{name: "Southern Illinois University - Carbondale"},
{name: "Trinity Christian College"},
{name: "Trinity International University"},
{name: "University of Illinois at Urbana/Champaign"},
{name: "University of Chicago"},
{name: "University of Illinois at Chicago"},
{name: "University of Illinois at Springfield"},
{name: "University of Saint Francis"},
{name: "VanderCook College of Music"},
{name: "Western Illinois University"},
{name: "Wheaton College"},
{name: "American College of Education"},
{name: "Anderson University"},
{name: "Ball State University"},
{name: "Bethel College"},
{name: "Butler University"},
{name: "Calumet College of St.  Joseph"},
{name: "DePauw University"},
{name: "Earlham College"},
{name: "Franklin College"},
{name: "Goshen College"},
{name: "Grace College"},
{name: "Hanover College"},
{name: "Holy Cross College"},
{name: "Huntington University"},
{name: "Indiana Institute of Technology"},
{name: "Indiana State University"},
{name: "Indiana University Bloomington"},
{name: "Indiana University East"},
{name: "Indiana University Kokomo"},
{name: "Indiana University Northwest"},
{name: "Indiana University Purdue University Columbus"},
{name: "Indiana University Purdue University Fort Wayne"},
{name: "Indiana University Purdue University Indianapolis"},
{name: "Indiana University South Bend"},
{name: "Indiana University Southeast"},
{name: "Indiana Wesleyan University"},
{name: "Manchester College"},
{name: "Marian University"},
{name: "Oakland City University"},
{name: "Purdue University"},
{name: "Purdue University Calumet"},
{name: "Purdue University North Central"},
{name: "Saint Joseph's College"},
{name: "Saint Mary's College"},
{name: "Saint Mary-of-the-Woods College"},
{name: "Taylor University"},
{name: "Trine University"},
{name: "University of Evansville"},
{name: "University of Indianapolis"},
{name: "University of Notre Dame"},
{name: "University of Phoenix - IN"},
{name: "University of Saint Francis"},
{name: "University of Southern Indiana"},
{name: "Valparaiso University"},
{name: "Vincennes University"},
{name: "Wabash College"},
{name: "Ashford University"},
{name: "Briar Cliff University"},
{name: "Buena Vista University"},
{name: "Central College"},
{name: "Clarke University"},
{name: "Coe College"},
{name: "Cornell College"},
{name: "Dordt College"},
{name: "Drake University"},
{name: "Emmaus Bible College"},
{name: "Faith Baptist Bible College"},
{name: "Graceland University"},
{name: "Grand View University"},
{name: "Grinnell College"},
{name: "Iowa State University"},
{name: "Iowa Wesleyan College"},
{name: "Kaplan University"},
{name: "Loras College"},
{name: "Luther College"},
{name: "Maharishi University of Management"},
{name: "Morningside College"},
{name: "Mt. Mercy University"},
{name: "Northwestern College"},
{name: "Regents Alternative Pathway to Iowa Licensure"},
{name: "Simpson College"},
{name: "St. Ambrose University"},
{name: "University of Dubuque"},
{name: "University of Iowa"},
{name: "University of Northern Iowa"},
{name: "Upper Iowa University"},
{name: "Waldorf College"},
{name: "Wartburg College"},
{name: "William Penn University"},
{name: "Baker University"},
{name: "Barclay"},
{name: "Benedictine College"},
{name: "Bethany College"},
{name: "Bethel College - KS"},
{name: "Central Christian College"},
{name: "Donnelly"},
{name: "Emporia State University"},
{name: "Fort Hays State University"},
{name: "Friends University"},
{name: "Haskell Indian Nations University"},
{name: "Kansas State University"},
{name: "Kansas Wesleyan University"},
{name: "McPherson College"},
{name: "MidAmerica Nazarene University"},
{name: "Newman University"},
{name: "Ottawa University"},
{name: "Pittsburg State University"},
{name: "Southwestern College - KS"},
{name: "Sterling College"},
{name: "Tabor College"},
{name: "University of Kansas"},
{name: "University of Saint Mary"},
{name: "Washburn University"},
{name: "Wichita State University"},
{name: "Alice Lloyd College"},
{name: "Asbury University"},
{name: "Bellarmine University"},
{name: "Berea College"},
{name: "Boyce College"},
{name: "Brescia University"},
{name: "Campbellsville University"},
{name: "Centre College"},
{name: "Eastern Kentucky University"},
{name: "Georgetown College"},
{name: "Jefferson County Public Schools ACES Program"},
{name: "Kentucky Christian University"},
{name: "Kentucky State University"},
{name: "Kentucky Wesleyan College"},
{name: "Lindsey Wilson College"},
{name: "Midway University"},
{name: "Morehead State University"},
{name: "Murray State University"},
{name: "Northern Kentucky University"},
{name: "Spalding University"},
{name: "St. Catharine College"},
{name: "Teach for America - KY"},
{name: "Thomas More College"},
{name: "Transylvania University"},
{name: "Union College - KY"},
{name: "University of Kentucky"},
{name: "University of Louisville"},
{name: "University of Pikeville"},
{name: "University of the Cumberlands"},
{name: "Western Kentucky University"},
{name: "Centenary College"},
{name: "Grambling State University"},
{name: "iTeach Louisiana"},
{name: "Louisiana College"},
{name: "Louisiana Resource Center for Educators"},
{name: "Louisiana State Univ - Shreveport"},
{name: "Louisiana State University - Alexandria"},
{name: "Louisiana State University - Baton Rouge"},
{name: "Louisiana Tech University"},
{name: "Loyola University of New Orleans"},
{name: "McNeese State University"},
{name: "Nicholls State University"},
{name: "Northwestern State University"},
{name: "Relay Graduate School of Education - LA"},
{name: "Southeastern Louisiana University"},
{name: "Southern University - New Orleans"},
{name: "Southern University A and M College"},
{name: "St. Bernard Parish Schools"},
{name: "Teach Ascension Academy"},
{name: "The New Teacher Project - LA"},
{name: "Tulane University"},
{name: "University of Holy Cross"},
{name: "University of LA at Lafayette"},
{name: "University of LA at Monroe"},
{name: "University of New Orleans"},
{name: "Xavier University of LA"},
{name: "Bates College"},
{name: "Bowdoin College"},
{name: "Colby College"},
{name: "College of the Atlantic"},
{name: "Husson University"},
{name: "Maine College of Art"},
{name: "Maine State Department of Education"},
{name: "St. Joseph's College"},
{name: "Thomas College"},
{name: "Unity College - ME"},
{name: "University of Maine"},
{name: "University of Maine at Farmington"},
{name: "University of Maine at Fort Kent"},
{name: "University of Maine at Machias"},
{name: "University of Maine at Presque Isle"},
{name: "University of New England"},
{name: "University of Southern Maine"},
{name: "College of the Marshall Islands"},
{name: "University of the South Pacific"},
{name: "Anne Arundel Community College/Anne Arundel County Public Schools"},
{name: "Anne Arundel County Public Schools/Notre Dame of Maryland University"},
{name: "Baltimore City Public Schools/Teach for America"},
{name: "Baltimore City Public Schools/Urban Teachers"},
{name: "Baltimore City Teaching Residency/The New Teacher Project(BCTR)"},
{name: "Baltimore County Public Schools/ Goucher College"},
{name: "Bowie State University"},
{name: "Coppin State University"},
{name: "Frostburg State University"},
{name: "Goucher College"},
{name: "Hood College"},
{name: "Johns Hopkins University"},
{name: "Loyola University Maryland"},
{name: "Maryland Department of Education"},
{name: "Maryland Institute College of Art (MICA)"},
{name: "McDaniel College"},
{name: "Montgomery County Public Schools/Montgomery Community College"},
{name: "Morgan State University"},
{name: "Mt. St. Mary's University - MD"},
{name: "Notre Dame of Maryland University"},
{name: "Peabody Institute"},
{name: "Prince George's County Public Schools/Resident Teacher Project"},
{name: "Prince George's County Public Schools/Teach for America"},
{name: "Prince Georges Co Public Schools/Notre Dame of Maryland University"},
{name: "Salisbury University"},
{name: "St. Mary's College of Maryland"},
{name: "Stevenson University"},
{name: "Towson University"},
{name: "University of Maryland Baltimore County"},
{name: "University of Maryland College Park"},
{name: "University of Maryland Eastern Shore"},
{name: "University of Maryland University College"},
{name: "Washington Adventist University"},
{name: "Washington College"},
{name: "American International College"},
{name: "Anna Maria College"},
{name: "Assumption College"},
{name: "Bay Path University"},
{name: "Becker College"},
{name: "Berklee College of Music"},
{name: "Boston College"},
{name: "Boston Conservatory"},
{name: "Boston Teacher Residency"},
{name: "Boston University"},
{name: "Brandeis University"},
{name: "Bridgewater State University"},
{name: "Cambridge College"},
{name: "Catherine Leahy Brine Educational Consultants, Inc."},
{name: "City on a Hill Charter Public School Circuit Street (District)"},
{name: "Clark University"},
{name: "Collaborative for Educational Services - MA"},
{name: "College of the Holy Cross"},
{name: "Curry College"},
{name: "DeLet"},
{name: "Eastern Nazarene"},
{name: "Elms College"},
{name: "Emerson College"},
{name: "Emmanuel College"},
{name: "Endicott College"},
{name: "Fitchburg State University"},
{name: "Framingham State University"},
{name: "Francis W. Parker Charter Essential (District)"},
{name: "Gordon College"},
{name: "Harvard Graduate School of Education"},
{name: "Hellenic College"},
{name: "Lasell College"},
{name: "Lesley University"},
{name: "Massachusetts College of Art"},
{name: "Massachusetts College of Liberal Arts (MCLA)"},
{name: "MATCH Charter Public School (District)"},
{name: "Merrimack College"},
{name: "Montserrat College of Art"},
{name: "Mount Holyoke College"},
{name: "Mount Ida College"},
{name: "Newton"},
{name: "Nichols College"},
{name: "Northeast Consortium for Staff Development (NCSD)"},
{name: "Northeastern University"},
{name: "PRISM Educational Consultants, Inc."},
{name: "Regis College"},
{name: "Salem State University"},
{name: "Shady Hill"},
{name: "Simmons College"},
{name: "Smith College"},
{name: "South Coast Educational Collaborative"},
{name: "Springfield College"},
{name: "Stonehill College"},
{name: "Suffolk University"},
{name: "Teach for America - MA"},
{name: "The Teachers' Loft"},
{name: "Tufts University"},
{name: "University of Massachusetts - Amherst"},
{name: "University of Massachusetts - Boston"},
{name: "University of Massachusetts - Dartmouth"},
{name: "University of Massachusetts - Lowell"},
{name: "Wellesley College"},
{name: "Western New England University"},
{name: "Westfield State University"},
{name: "Wheaton College"},
{name: "Wheelock College"},
{name: "Worcester Polytechnic Institute"},
{name: "Worcester State University"},
{name: "Adrian college"},
{name: "Albion College"},
{name: "Alma College"},
{name: "Andrews University"},
{name: "Aquinas College"},
{name: "Baker College"},
{name: "Calvin College"},
{name: "Central Michigan University"},
{name: "College for Creative Studies"},
{name: "Concordia University"},
{name: "Cornerstone University"},
{name: "Eastern Michigan University"},
{name: "Ferris State University"},
{name: "Grand Valley State University"},
{name: "Hope College"},
{name: "Lake Superior State University"},
{name: "Madonna University"},
{name: "Marygrove College"},
{name: "Michigan State University"},
{name: "Michigan Technological University"},
{name: "Northern Michigan University"},
{name: "Oakland University"},
{name: "Olivet College"},
{name: "Robert B. Miller College"},
{name: "Rochester College"},
{name: "Saginaw Valley State University"},
{name: "Schoolcraft College"},
{name: "Siena Heights University"},
{name: "Spring Arbor University"},
{name: "The New Teacher Project/Michigan Teacher Corps"},
{name: "University of Detroit Mercy"},
{name: "University of Michigan - Ann Arbor"},
{name: "University of Michigan - Dearborn"},
{name: "University of Michigan - Flint"},
{name: "Wayne State University"},
{name: "Western Michigan University"},
{name: "College of Micronesia"},
{name: "Augsburg College"},
{name: "Bemidji State University"},
{name: "Bethany Lutheran College"},
{name: "Bethel University"},
{name: "Carleton College"},
{name: "College of St. Benedict & St. John’s University"},
{name: "College of St. Scholastica"},
{name: "Concordia College - Moorhead"},
{name: "Concordia University - St. Paul"},
{name: "Crown College"},
{name: "Gustavus Adolphus College"},
{name: "Hamline University"},
{name: "Martin Luther College"},
{name: "Metropolitian State University"},
{name: "Minnesota State University - Mankato"},
{name: "Minnesota State University - Moorhead"},
{name: "North Central University"},
{name: "Saint Mary's University"},
{name: "Southwest Minnesota State University"},
{name: "St. Catherine University"},
{name: "St. Cloud State University"},
{name: "St. Olaf College"},
{name: "University of Minnesota Crookston"},
{name: "University of Minnesota Duluth"},
{name: "University of Minnesota Morris"},
{name: "University of Minnesota Twin Cities"},
{name: "University of Northwestern – St. Paul"},
{name: "University of St. Thomas"},
{name: "Walden University"},
{name: "Winona State University"},
{name: "Alcorn State University"},
{name: "American Board for Certification of Teacher Excellence- MS"},
{name: "Belhaven University"},
{name: "Blue Mountain College"},
{name: "Delta State University"},
{name: "Jackson State University"},
{name: "Millsaps College"},
{name: "Mississippi College"},
{name: "Mississippi Community College Foundation"},
{name: "Mississippi State University"},
{name: "Mississippi Valley State University"},
{name: "Missississippi  University for Women"},
{name: "Rust College"},
{name: "Teach For America - MS"},
{name: "Teach Mississippi Institute online"},
{name: "The University of Southern Mississippi"},
{name: "Tougaloo College"},
{name: "University of Mississippi"},
{name: "William Carey University"},
{name: "American Board for Certification of Teacher Excellence- MO"},
{name: "Avila University"},
{name: "Baptist Bible College"},
{name: "Calvary Bible College"},
{name: "Central Methodist University"},
{name: "College of the Ozarks"},
{name: "Columbia College"},
{name: "Culver-Stockton College"},
{name: "Drury University"},
{name: "Evangel University"},
{name: "Fontbonne University"},
{name: "Hannibal-LaGrange University"},
{name: "Harris-Stowe State University"},
{name: "Kansas City Art Institution"},
{name: "Lincoln University"},
{name: "Lindenwood University"},
{name: "Maryville University"},
{name: "Missouri Baptist University"},
{name: "Missouri Southern State University"},
{name: "Missouri State University"},
{name: "Missouri University of Science and Technology"},
{name: "Missouri Valley College"},
{name: "Missouri Western State University"},
{name: "Northwest Missouri State University"},
{name: "Park University"},
{name: "Rockhurst University"},
{name: "Saint Louis University"},
{name: "Southeast Missouri State University"},
{name: "Southwest Baptist University"},
{name: "Stephens College"},
{name: "Temporary Authorization"},
{name: "Truman State University"},
{name: "University of Central Missouri"},
{name: "University of Missouri - Columbia"},
{name: "University of Missouri - Kansas City"},
{name: "University of Missouri - St. Louis"},
{name: "University of Phoenix - MO"},
{name: "Washington University"},
{name: "Webster University"},
{name: "Western Governors University - MO"},
{name: "Westminster College"},
{name: "William Jewell College"},
{name: "William Woods University"},
{name: "Carroll College"},
{name: "Montana State University-Billings"},
{name: "Montana State University-Bozeman"},
{name: "Montana State University-Northern"},
{name: "Rocky Mountain College"},
{name: "Salish Kootenai College"},
{name: "University of Great Falls"},
{name: "University of Montana"},
{name: "University of Montana-Western"},
{name: "Chadron State College"},
{name: "College of St. Mary"},
{name: "Concordia University"},
{name: "Creighton University"},
{name: "Doane University"},
{name: "Grace University"},
{name: "Hastings College"},
{name: "Midland University"},
{name: "Nebraska Wesleyan University"},
{name: "Peru State College"},
{name: "Union College - NE"},
{name: "University of Nebraska - Kearney"},
{name: "University of Nebraska - Lincoln"},
{name: "University of Nebraska - Omaha"},
{name: "Wayne State College"},
{name: "York College"},
{name: "Clark County School District"},
{name: "Great Basin College"},
{name: "Humboldt County School District"},
{name: "National University"},
{name: "Nevada State College"},
{name: "Nova Southeastern University"},
{name: "Sierra Nevada College"},
{name: "Touro University"},
{name: "University of Nevada Las Vegas (UNLV)"},
{name: "University of Nevada Reno (UNR)"},
{name: "University of Phoenix - NV"},
{name: "Washoe County School District"},
{name: "Western Governors University - NV"},
{name: "American Board for Certification of Teacher Excellence - NH"},
{name: "Antioch University New England"},
{name: "Colby Sawyer College"},
{name: "Dartmouth College"},
{name: "Franklin Pierce University"},
{name: "Granite State College"},
{name: "Keene State College"},
{name: "New England College"},
{name: "New Hampshire Institute of Art"},
{name: "NH State Department of Education"},
{name: "NHTI - Concord's Community College"},
{name: "Plymouth State University"},
{name: "Rivier University"},
{name: "Saint Anselm College"},
{name: "Southern New Hampshire University"},
{name: "University of New Hampshire"},
{name: "Upper Valley Educator Institute"},
{name: "Bloomfield College"},
{name: "Caldwell University"},
{name: "Centenary College"},
{name: "College of Saint Elizabeth"},
{name: "Drew University"},
{name: "Fairleigh Dickinson University"},
{name: "Felician College"},
{name: "Georgian Court Univeristy"},
{name: "Kean University"},
{name: "Monmouth University"},
{name: "Montclair State University"},
{name: "New Jersey City University"},
{name: "NJ Department of Education Alternate Route"},
{name: "Princeton University"},
{name: "Ramapo College"},
{name: "RELAY Graduate School of Education - NJ"},
{name: "Rider University"},
{name: "Rowan University"},
{name: "Rutgers University - Camden"},
{name: "Rutgers University - New Brunswick"},
{name: "Rutgers University - Newark"},
{name: "Saint Peters University"},
{name: "Seton Hall University"},
{name: "Stockton University"},
{name: "The College of New Jersey"},
{name: "William Paterson University"},
{name: "Central New Mexico Community College"},
{name: "Eastern New Mexico University"},
{name: "New Mexico Highlands University"},
{name: "New Mexico Junior College"},
{name: "New Mexico State University"},
{name: "Northern New Mexico College"},
{name: "San Juan College"},
{name: "Santa Fe Community College"},
{name: "University of New Mexico"},
{name: "University of Phoenix - NM"},
{name: "University of the Southwest"},
{name: "Wayland Baptist University"},
{name: "Western Governors University - NM"},
{name: "Western New Mexico University"},
{name: "Adelphi University"},
{name: "Alfred University - Main"},
{name: "Bank Street College of Ed."},
{name: "Bard College"},
{name: "Barnard College"},
{name: "Boricua College"},
{name: "Canisius College of Buffalo"},
{name: "Cazenovia College"},
{name: "Clarkson University"},
{name: "Colgate University"},
{name: "College of Mt. St. Vincent"},
{name: "College of New Rochelle - Main"},
{name: "College of St. Rose"},
{name: "Concordia College"},
{name: "CUNY Brooklyn College"},
{name: "CUNY City College"},
{name: "CUNY College of Staten Island"},
{name: "CUNY Herbert H. Lehman College"},
{name: "CUNY Hunter College"},
{name: "CUNY Medgar Evers College"},
{name: "CUNY NYC College of Technology"},
{name: "CUNY Queens College"},
{name: "CUNY York College"},
{name: "D'Youville College"},
{name: "Daemen College"},
{name: "Dominican College of Blauvelt"},
{name: "Dowling College Oakdale"},
{name: "Dowling College-Brookhaven Campus"},
{name: "Elmira College"},
{name: "Five Towns College"},
{name: "Fordham University"},
{name: "Hartwick College"},
{name: "Hobart and William Smith Colleges"},
{name: "Hofstra University - Main"},
{name: "Houghton College"},
{name: "Iona College - New Rochelle"},
{name: "Iona College - Rockland"},
{name: "Ithaca College"},
{name: "Keuka College"},
{name: "LIU - Brentwood"},
{name: "LIU - Brooklyn"},
{name: "LIU - C.W. Post"},
{name: "LIU - Riverhead"},
{name: "LIU - Rockland"},
{name: "LIU - Westchester"},
{name: "Le Moyne College"},
{name: "Manhattan College"},
{name: "Manhattanville College"},
{name: "Marist College"},
{name: "Medaille College"},
{name: "Mercy College - Bronx"},
{name: "Mercy College - Main"},
{name: "Mercy College - Manhattan Campus"},
{name: "Mercy College - Yorktown Hgts."},
{name: "Metropolitan College of New York"},
{name: "Molloy College"},
{name: "Monroe College"},
{name: "Mount St. Mary College - NY"},
{name: "Nazareth College of Rochester"},
{name: "New York Institute of Technology - Old Westbury"},
{name: "New York Medical College"},
{name: "New York University - Main"},
{name: "Niagara University"},
{name: "NY Institute of Technology - Manhattan"},
{name: "Nyack College"},
{name: "Pace University - NYC"},
{name: "Pace University-Pleasantville"},
{name: "Pratt Institute"},
{name: "Relay School of Education - NY"},
{name: "Roberts Wesleyan College"},
{name: "Rochester Inst. of Technology"},
{name: "Sage Colleges (The) - Albany"},
{name: "Sage Colleges (The) - Troy"},
{name: "Sarah Lawrence College"},
{name: "School of Visual Arts - NY"},
{name: "Siena College"},
{name: "Skidmore College"},
{name: "St John's University - Staten Island"},
{name: "St. Bonaventure University"},
{name: "St. Francis College"},
{name: "St. John Fisher College"},
{name: "St. John's University - Main"},
{name: "St. Joseph's College-Main"},
{name: "St. Joseph's College-Suffolk"},
{name: "St. Lawrence University"},
{name: "St. Thomas Aquinas College"},
{name: "SUNY Brockport"},
{name: "SUC Buffalo"},
{name: "SUNY Cortland"},
{name: "SUNY Fredonia"},
{name: "SUNY Geneseo"},
{name: "SUNY New Paltz"},
{name: "SUNY Old Westbury"},
{name: "SUNY Oneonta"},
{name: "SUNY Oswego"},
{name: "SUNY Plattsburgh"},
{name: "SUNY Plattsburgh at ACC"},
{name: "SUNY Potsdam"},
{name: "SUNY Empire State College"},
{name: "SUNY Albany"},
{name: "SUNY Binghamton"},
{name: "SUNY Buffalo"},
{name: "SUNY Stony Brook"},
{name: "Syracuse University"},
{name: "Teachers College at Columbia University"},
{name: "The American Museum of Natural History"},
{name: "Touro College - Bay Shore Campus"},
{name: "Touro College - Flatbush"},
{name: "Touro College - Manhattan"},
{name: "University of Rochester"},
{name: "Utica College"},
{name: "Vassar College"},
{name: "Wagner College"},
{name: "Wells College"},
{name: "Yeshiva University"},
{name: "Appalachian State University"},
{name: "Barton College"},
{name: "Belmont Abbey College"},
{name: "Bennett College"},
{name: "Brevard College"},
{name: "Campbell University"},
{name: "Catawba  College"},
{name: "Catawba Regional Alternative Licensing Center"},
{name: "Charlotte Regional Alternative Licensing Center"},
{name: "Chowan University"},
{name: "Duke  University"},
{name: "East Carolina University"},
{name: "Elizabeth City State University"},
{name: "Elon University"},
{name: "Fayetteville Regional Alternative Licensing Center"},
{name: "Fayetteville State University"},
{name: "Gardner-Webb University"},
{name: "Greensboro College"},
{name: "Guilford College"},
{name: "High Point University"},
{name: "Lees-McRae College"},
{name: "Lenoir-Rhyne  University"},
{name: "Livingstone College"},
{name: "Mars Hill University"},
{name: "Meredith College"},
{name: "Methodist University"},
{name: "Mid-Atlantic Christian University"},
{name: "Nash Regional Alternative Licensing Center"},
{name: "North Carolina A&T State University"},
{name: "North Carolina Central University"},
{name: "North Carolina State University"},
{name: "North Carolina Wesleyan College"},
{name: "Pfeiffer University"},
{name: "Queens University of Charlotte"},
{name: "Saint Augustine's University"},
{name: "Salem College"},
{name: "Shaw University"},
{name: "St. Andrews University"},
{name: "TEACH Charlotte TNTP"},
{name: "University of Mount Olive"},
{name: "University of North Carolina-Asheville"},
{name: "University of North Carolina-Chapel Hill"},
{name: "University of North Carolina-Charlotte"},
{name: "University of North Carolina-Greensboro"},
{name: "University of North Carolina-Pembroke"},
{name: "University of North Carolina-Wilmington"},
{name: "Wake Forest University"},
{name: "Western Carolina University"},
{name: "William Peace University"},
{name: "Wingate University"},
{name: "Winston-Salem State University"},
{name: "Dickinson State University"},
{name: "Fort Berthold Community College"},
{name: "Jamestown University"},
{name: "Mayville State University"},
{name: "Minot State University"},
{name: "North Dakota State University"},
{name: "Sitting Bull College"},
{name: "Turtle Mountain Community College"},
{name: "United Tribes Technical College"},
{name: "University of Mary"},
{name: "University of North Dakota"},
{name: "Valley City State University"},
{name: "Northern Marianas College"},
{name: "Antioch University Midwest"},
{name: "Ashland University"},
{name: "Baldwin Wallace University"},
{name: "Bluffton University"},
{name: "Bowling Green State University"},
{name: "Capital University"},
{name: "Case Western Reserve University"},
{name: "Cedarville University"},
{name: "Central State University"},
{name: "Cincinnati Christian University"},
{name: "Cleveland State University"},
{name: "Defiance College"},
{name: "Franciscan University of Steubenville"},
{name: "Heidelberg University"},
{name: "Hiram College"},
{name: "Indiana Wesleyan University"},
{name: "John Carroll University"},
{name: "Kent State University"},
{name: "Lake Erie College"},
{name: "Lourdes University"},
{name: "Malone University"},
{name: "Marietta College"},
{name: "Miami University"},
{name: "Mount St. Joseph University"},
{name: "Mount Vernon Nazarene University"},
{name: "Muskingum University"},
{name: "Notre Dame College of Ohio"},
{name: "Oberlin College"},
{name: "Ohio Christian University"},
{name: "Ohio Dominican University"},
{name: "Ohio Northern University"},
{name: "Ohio University"},
{name: "Ohio Wesleyan University"},
{name: "Otterbein University"},
{name: "Shawnee State University"},
{name: "The College of Wooster"},
{name: "The Ohio State University"},
{name: "The University of Akron"},
{name: "The University of Toledo"},
{name: "University of Cincinnati"},
{name: "University of Dayton"},
{name: "University of Findlay"},
{name: "University of Mount Union"},
{name: "University of Rio Grande"},
{name: "Urbana University"},
{name: "Ursuline College"},
{name: "Walsh University"},
{name: "Wilmington College"},
{name: "Wittenberg University"},
{name: "Wright State University"},
{name: "Xavier University"},
{name: "Youngstown State University"},
{name: "Bacone College"},
{name: "Cameron University"},
{name: "East Central University"},
{name: "Langston University"},
{name: "Mid-America Christian University"},
{name: "Northeastern State University"},
{name: "Northwestern Oklahoma State University"},
{name: "Oklahoma Baptist University"},
{name: "Oklahoma Christian University"},
{name: "Oklahoma City University"},
{name: "Oklahoma Panhandle State University"},
{name: "Oklahoma State University"},
{name: "Oklahoma Wesleyan University"},
{name: "Oral Roberts University"},
{name: "Southeastern Oklahoma State University"},
{name: "Southern Nazarene University"},
{name: "Southwestern Oklahoma State University"},
{name: "St. Gregory's University"},
{name: "State Of Oklahoma Department of Education"},
{name: "University of Central Oklahoma"},
{name: "University of Oklahoma"},
{name: "University of Science and Arts of Oklahoma"},
{name: "University of Tulsa"},
{name: "Concordia University-Oregon"},
{name: "Corban University"},
{name: "Eastern Oregon University"},
{name: "George Fox University"},
{name: "Lewis and Clark College"},
{name: "Linfield College"},
{name: "Marylhurst University"},
{name: "Multnomah University"},
{name: "Northwest Christian University"},
{name: "Oregon State University"},
{name: "Pacific University"},
{name: "Portland State University"},
{name: "Southern Oregon University"},
{name: "University of Oregon"},
{name: "University of Phoenix - OR"},
{name: "University of Portland"},
{name: "Warner Pacific College"},
{name: "Western Oregon University"},
{name: "Albright College"},
{name: "Alvernia University"},
{name: "American Board for Certification of Teacher Excellence - PA"},
{name: "Arcadia University"},
{name: "Baptist Bible Col and Seminary"},
{name: "Bloomsburg University of PA"},
{name: "Bryn Mawr College"},
{name: "Bucknell University"},
{name: "Cabrini College"},
{name: "Cairn University"},
{name: "California University of PA"},
{name: "Carlow University"},
{name: "Carnegie-Mellon University"},
{name: "Cedar Crest College"},
{name: "Chatham University"},
{name: "Chestnut Hill College"},
{name: "Cheyney University of PA"},
{name: "Clarion Univ of PA/ Main"},
{name: "Delaware Valley College"},
{name: "DeSales University"},
{name: "Dickinson College"},
{name: "Drexel University"},
{name: "Duquesne University"},
{name: "East Stroudsburg University of PA"},
{name: "Eastern University"},
{name: "Edinboro University of PA"},
{name: "Elizabethtown College"},
{name: "Gannon University"},
{name: "Geneva College"},
{name: "Gettysburg College"},
{name: "Grove City College"},
{name: "Gwynedd-Mercy College"},
{name: "Holy Family University"},
{name: "Immaculata University"},
{name: "Indiana University of PA"},
{name: "Juniata College"},
{name: "Keystone College"},
{name: "King's College"},
{name: "Kutztown University of PA"},
{name: "La Roche College"},
{name: "La Salle University"},
{name: "Lancaster Bible College"},
{name: "Lebanon Valley College"},
{name: "Lehigh University"},
{name: "Lincoln University"},
{name: "Lock Haven Univ of PA/ Main"},
{name: "Lycoming College"},
{name: "Mansfield University of PA"},
{name: "Marywood University"},
{name: "Mercyhurst College"},
{name: "Messiah College"},
{name: "Millersville University of PA"},
{name: "Misericordia University"},
{name: "Moore College of Art & Design"},
{name: "Moravian College/Theological Seminary"},
{name: "Mount Aloysius College"},
{name: "Muhlenberg College"},
{name: "Neumann University"},
{name: "Penn State University – University Park"},
{name: "Penn State University Harrisburg"},
{name: "Point Park University"},
{name: "Robert Morris University"},
{name: "Rosemont College"},
{name: "Saint Francis University"},
{name: "Saint Joseph's University"},
{name: "Saint Vincent College"},
{name: "Salus University"},
{name: "Seton Hill University"},
{name: "Shippensburg University of PA"},
{name: "Slippery Rock University of PA"},
{name: "Susquehanna University"},
{name: "Swarthmore College"},
{name: "Temple University"},
{name: "Thiel College"},
{name: "University of Pennsylvania"},
{name: "University of Pgh/Main"},
{name: "University of Pgh/Bradford Cmp"},
{name: "University of Pgh/Greensburg Cmp"},
{name: "University of Pgh/Johnstn Cmp"},
{name: "University of Scranton"},
{name: "University of the Arts (The)"},
{name: "University of Valley Forge"},
{name: "Ursinus College"},
{name: "Villanova University"},
{name: "Washington and Jefferson Coll"},
{name: "Waynesburg University"},
{name: "West Chester University of PA"},
{name: "Westminster College"},
{name: "Widener University"},
{name: "Wilkes University"},
{name: "Wilson College"},
{name: "York College of Pennsylvania"},
{name: "American University of Puerto Rico, Recinto de Bayamon"},
{name: "Caribbean University - Recinto de Bayamon"},
{name: "Caribbean University - Recinto de Carolina"},
{name: "Caribbean University - Recinto de Ponce"},
{name: "Caribbean University - Recinto de Vega Baja"},
{name: "Conservatorio de Música de Puerto Rico"},
{name: "Dewey University"},
{name: "Escuela de Artes Plásticas de Puerto Rico"},
{name: "National University College- Arecibo Campus"},
{name: "National University College- Bayamon Main Campus"},
{name: "National University College- Rio Grande Campus"},
{name: "Pontificia Universidad Católica de Puerto Rico, Arecibo"},
{name: "Pontificia Universidad Católica de Puerto Rico, Mayaguez"},
{name: "Pontificia Universidad Católica de Puerto Rico, Ponce"},
{name: "Universidad Adventista de las Antillas"},
{name: "Universidad Central de Bayamón"},
{name: "Universidad de Puerto Rico, Recinto de Aguadilla"},
{name: "Universidad de Puerto Rico, Recinto de Arecibo"},
{name: "Universidad de Puerto Rico, Recinto de Bayamon"},
{name: "Universidad de Puerto Rico, Recinto de Cayey"},
{name: "Universidad de Puerto Rico, Recinto de Humacao"},
{name: "Universidad de Puerto Rico, Recinto de Mayaguez"},
{name: "Universidad de Puerto Rico, Recinto de Ponce"},
{name: "Universidad de Puerto Rico, Recinto de Rio Piedras"},
{name: "Universidad de Puerto Rico, Recinto de Utuado"},
{name: "Universidad del Este (Sistema Universitario Ana G. Mendez)"},
{name: "Universidad del Sagrado Corazón"},
{name: "Universidad del Turabo, Gurabo (Sistema Universitario Ana G. Mendez)"},
{name: "Universidad dePuerto Rico, Recinto Carolina"},
{name: "Universidad Interamericana de Puerto Rico, Recinto de Aguadilla"},
{name: "Universidad Interamericana de Puerto Rico, Recinto de Arecibo"},
{name: "Universidad Interamericana de Puerto Rico, Recinto de Barranquitas"},
{name: "Universidad Interamericana de Puerto Rico, Recinto de Fajardo"},
{name: "Universidad Interamericana de Puerto Rico, Recinto de Guayama"},
{name: "Universidad Interamericana de Puerto Rico, Recinto de Ponce"},
{name: "Universidad Interamericana de Puerto Rico, Recinto de San Germán"},
{name: "Universidad Interamericana de Puerto Rico, Recinto Metropolitano"},
{name: "Universidad Metropolitana , Cupey (Sistema Universitario Ana G. Mendez)"},
{name: "Brown University"},
{name: "Johnson & Wales University"},
{name: "Providence College"},
{name: "Rhode Island College"},
{name: "Rhode Island School of Design"},
{name: "Roger Williams University"},
{name: "Salve Regina University"},
{name: "Teach For America, RI"},
{name: "University of Rhode Island"},
{name: "American Board for Certification of Teaching Excellence- SC"},
{name: "Anderson University"},
{name: "Benedict College"},
{name: "Bob Jones University"},
{name: "Charleston Southern University"},
{name: "Claflin University"},
{name: "Clemson University"},
{name: "Coastal Carolina University"},
{name: "Coker College"},
{name: "College of Charleston"},
{name: "Columbia College"},
{name: "Columbia International University"},
{name: "Converse College"},
{name: "Erskine College"},
{name: "Francis Marion University"},
{name: "Furman University"},
{name: "Lander University"},
{name: "Limestone College"},
{name: "Morris College"},
{name: "Newberry College"},
{name: "North Greenville University"},
{name: "Presbyterian College"},
{name: "Program of Alternative Certification for Educators (PACE) Program - SCDE"},
{name: "South Carolina State University"},
{name: "Southern Wesleyan University"},
{name: "Teach for America - SC"},
{name: "The Citadel"},
{name: "University of South Carolina - Aiken"},
{name: "University of South Carolina - Beaufort"},
{name: "University of South Carolina - Columbia"},
{name: "University of South Carolina - Upstate"},
{name: "Winthrop University"},
{name: "Wofford College"},
{name: "Augustana University"},
{name: "Black Hills State University"},
{name: "Dakota State University"},
{name: "Dakota Wesleyan University"},
{name: "Mount Marty College"},
{name: "Northern State University"},
{name: "Oglala Lakota College"},
{name: "Presentation College"},
{name: "Sinte Gleska University"},
{name: "South Dakota State University"},
{name: "State of South Dakota"},
{name: "University of Sioux Falls"},
{name: "University of South Dakota"},
{name: "Aquinas College"},
{name: "Austin Peay State University"},
{name: "Belmont University"},
{name: "Bethel University"},
{name: "Bryan College"},
{name: "Carson-Newman University"},
{name: "Christian Brothers University"},
{name: "Cumberland University"},
{name: "East Tennessee State University"},
{name: "Fisk University"},
{name: "Freed-Hardeman University"},
{name: "Johnson University"},
{name: "King University"},
{name: "Lee University"},
{name: "Lemoyne-Owen College"},
{name: "Lincoln Memorial University"},
{name: "Lipscomb University"},
{name: "Martin Methodist College"},
{name: "Maryville College"},
{name: "Memphis College of Art"},
{name: "Middle Tennessee State University"},
{name: "Milligan College"},
{name: "Peabody College of Vanderbilt University"},
{name: "South College"},
{name: "Southern Adventist University"},
{name: "Teach for America - Memphis"},
{name: "TEACH Tennessee"},
{name: "Tennessee State University"},
{name: "Tennessee Technological University"},
{name: "Tennessee Wesleyan University"},
{name: "TNTP - Memphis Teaching Fellows"},
{name: "Trevecca Nazarene University"},
{name: "Tusculum College"},
{name: "Union University"},
{name: "University of Memphis"},
{name: "University of Tennessee - Chattanooga"},
{name: "University of Tennessee - Knoxville"},
{name: "University of Tennessee - Martin"},
{name: "Welch College"},
{name: "A Career in Education-ACP"},
{name: "A Career in Teaching-EPP (Corpus Christi)"},
{name: "A Career in Teaching-EPP (McAllen)"},
{name: "A+ Texas Teachers"},
{name: "Abilene Christian University"},
{name: "ACT - Rio Grande Valley"},
{name: "ACT - Central Texas"},
{name: "ACT - Houston"},
{name: "ACT - Houston at Dallas"},
{name: "ACT - San Antonio (Alt Cert for Teachers)"},
{name: "Alamo Colleges Educator Preparation Program"},
{name: "Alternative-South Texas Educator Program (A-STEP)"},
{name: "Angelo State University"},
{name: "Arlington Baptist College Teacher Certification Program (ABCTCP)"},
{name: "Austin College"},
{name: "Austin Community College"},
{name: "Baylor University"},
{name: "Concordia University"},
{name: "Dallas Baptist University"},
{name: "Dallas Christian College"},
{name: "Dallas ISD"},
{name: "East Texas Baptist University"},
{name: "Education Career Alternatives Program (ECAP) Texas"},
{name: "Educators of Excellence ACP"},
{name: "EIT: Excellence in Teaching"},
{name: "Hardin-Simmons University"},
{name: "Harris County Department of Education"},
{name: "Houston Baptist University"},
{name: "Houston Community College System (ACP)"},
{name: "Houston ISD"},
{name: "Howard Payne University"},
{name: "Huston-Tillotson University"},
{name: "Intern Teacher ACP"},
{name: "iteachTEXAS"},
{name: "Jarvis Christian College"},
{name: "Lamar University"},
{name: "LeTourneau University"},
{name: "Lonestar College - Kingwood"},
{name: "Lubbock Christian University"},
{name: "McLennan Community College"},
{name: "McMurry University"},
{name: "Midwestern State University"},
{name: "Mountain View College"},
{name: "North American College"},
{name: "Our Lady of the Lake University"},
{name: "Pasadena ISD"},
{name: "Paul Quinn College"},
{name: "Prairie View A&M University"},
{name: "Quality ACT: Alternative Certified Teachers - TX"},
{name: "Region 01 Education Service Center - TX"},
{name: "Region 02 Education Service Center - TX"},
{name: "Region 03 Education Service Center - TX"},
{name: "Region 04 Education Service Center - TX"},
{name: "Region 05 Education Service Center - TX"},
{name: "Region 06 Education Service Center - TX"},
{name: "Region 07 Education Service Center - TX"},
{name: "Region 10 Education Service Center - TX"},
{name: "Region 11 Education Service Center - TX"},
{name: "Region 12 Education Service Center - TX"},
{name: "Region 13 Education Service Center - TX"},
{name: "Region 14 Education Service Center - TX"},
{name: "Region 18 Education Service Center - TX"},
{name: "Region 19 Education Service Center - TX"},
{name: "Region 20 Education Service Center - TX"},
{name: "Relay GSE Houston"},
{name: "Rice University"},
{name: "Sam Houston State University"},
{name: "Schreiner University"},
{name: "South Texas College - Alternative Certification Program (STAC)"},
{name: "South Texas Transition to Teaching Alternative Certification Program"},
{name: "Southern Methodist University"},
{name: "Southwestern Adventist University"},
{name: "Southwestern Assemblies of God University"},
{name: "Southwestern University"},
{name: "St. Edward's University"},
{name: "St. Mary's University"},
{name: "Stephen F Austin State University"},
{name: "Sul Ross State University - Alpine"},
{name: "Sul Ross State University - Uvalde/Rio Grande"},
{name: "Tarleton State University"},
{name: "TeacherBuilder.com"},
{name: "Teachers for the 21st Century - TX"},
{name: "Texas A&M International University"},
{name: "Texas A&M University"},
{name: "Texas A&M University - Central Texas"},
{name: "Texas A&M University - Commerce"},
{name: "Texas A&M University - Corpus Christi"},
{name: "Texas A&M University - Kingsville"},
{name: "Texas A&M University - San Antonio"},
{name: "Texas A&M University - Texarkana"},
{name: "Texas Alternative Certification Program at Austin"},
{name: "Texas Alternative Certification Program at Brownsville"},
{name: "Texas Alternative Certification Program at Houston"},
{name: "Texas Alternative Certification Program at San Antonio"},
{name: "Texas Alternative Certification Program El Paso"},
{name: "Texas Christian University"},
{name: "Texas College"},
{name: "Texas Lutheran University"},
{name: "Texas Southern University"},
{name: "Texas State University"},
{name: "Texas Tech University"},
{name: "Texas Wesleyan University"},
{name: "Texas Womans University"},
{name: "The Texas Institute for Teacher Education"},
{name: "TNTP Academy - Fort Worth"},
{name: "Training via E-Learning: An Alternative Certification Hybrid (T.E.A.C.H.)"},
{name: "Trinity University"},
{name: "University of Dallas"},
{name: "University of Houston"},
{name: "University of Houston-Clear Lake"},
{name: "University of Houston-Downtown"},
{name: "University of Houston-Victoria"},
{name: "University of Mary Hardin-Baylor"},
{name: "University of North Texas"},
{name: "University of North Texas - Dallas"},
{name: "University of Phoenix - TX"},
{name: "University of St Thomas"},
{name: "University of Texas - Arlington"},
{name: "University of Texas - Austin"},
{name: "University of Texas - Brownsville"},
{name: "University of Texas - Dallas"},
{name: "University of Texas - El Paso"},
{name: "University of Texas - Permian Basin"},
{name: "University of Texas - Rio Grande Valley"},
{name: "University of Texas - San Antonio"},
{name: "University of Texas - Tyler"},
{name: "University of the Incarnate Word"},
{name: "Wayland Baptist University"},
{name: "Weatherford College"},
{name: "Web-Centric Alternative Certification Program"},
{name: "West Texas A&M University"},
{name: "Western Governors University TX"},
{name: "Wiley College"},
{name: "YES Preparatory Public Schools Inc"},
{name: "Brigham Young University"},
{name: "Dixie State College"},
{name: "Southern Utah University"},
{name: "University of Phoenix - UT"},
{name: "University of Utah"},
{name: "Utah State Office of Education (USOE) Alternative Route to Licensure (ARL)"},
{name: "Utah State University"},
{name: "Utah Valley University"},
{name: "Weber State University"},
{name: "Western Governors University - UT"},
{name: "Westminster College"},
{name: "Career and Technical Ed Teacher Prep Program - VT"},
{name: "Castleton State College"},
{name: "Champlain College"},
{name: "College of St. Joseph"},
{name: "Goddard College"},
{name: "Green Mountain College"},
{name: "Johnson State College"},
{name: "Lyndon State College"},
{name: "Middlebury College"},
{name: "Norwich University"},
{name: "Peer Review"},
{name: "Saint Michael's College"},
{name: "Spark Teacher Education Institute"},
{name: "Teacher Apprenticeship Program - VT"},
{name: "University of Vermont"},
{name: "University of the Virgin Islands"},
{name: "Averett University"},
{name: "Bluefield College"},
{name: "Bridgewater College"},
{name: "Christopher Newport University"},
{name: "College of William and Mary"},
{name: "Eastern Mennonite University"},
{name: "Emory & Henry College"},
{name: "Ferrum College"},
{name: "George Mason University"},
{name: "Hampton University"},
{name: "Hollins University"},
{name: "James Madison University"},
{name: "Liberty University"},
{name: "Longwood University"},
{name: "Lynchburg College"},
{name: "Mary Baldwin University"},
{name: "Marymount University"},
{name: "Norfolk State University"},
{name: "Old Dominion University"},
{name: "Radford University"},
{name: "Randolph College"},
{name: "Randolph-Macon College"},
{name: "Regent University"},
{name: "Roanoke College"},
{name: "Shenandoah University"},
{name: "Sweet Briar College"},
{name: "University of Mary Washington - COE"},
{name: "University of Richmond"},
{name: "University of Virginia"},
{name: "University of Virginia at Wise"},
{name: "Virginia Commonwealth University"},
{name: "Virginia Community College System"},
{name: "Virginia State University"},
{name: "Virginia Tech"},
{name: "Virginia Union University"},
{name: "Virginia Wesleyan College"},
{name: "Washington and Lee University"},
{name: "Antioch University Seattle"},
{name: "Central Washington University"},
{name: "City University of Seattle"},
{name: "Eastern Washington University"},
{name: "Gonzaga University"},
{name: "Heritage University"},
{name: "Northwest University"},
{name: "Pacific Lutheran University"},
{name: "Saint Martin's University"},
{name: "Seattle Pacific University"},
{name: "Seattle University"},
{name: "The Evergreen State College"},
{name: "University of Puget Sound"},
{name: "University of Washington-Bothell"},
{name: "University of Washington-Seattle"},
{name: "University of Washington-Tacoma"},
{name: "Walla Walla University"},
{name: "Washington State University"},
{name: "Western Governors University - WA"},
{name: "Western Washington University"},
{name: "Whitworth University"},
{name: "Alderson Broaddus"},
{name: "American Public University System"},
{name: "Appalachian Bible College"},
{name: "Bethany College"},
{name: "Bluefield State College"},
{name: "Concord University"},
{name: "Davis & Elkins College"},
{name: "Fairmont State University"},
{name: "Glenville State College"},
{name: "Marshall University"},
{name: "Ohio Valley University"},
{name: "Salem International University"},
{name: "Shepherd University"},
{name: "University of Charleston"},
{name: "West Liberty University"},
{name: "West Virginia State University"},
{name: "West Virginia University"},
{name: "West Virginia University-Parkersburg"},
{name: "West Virginia Wesleyan College"},
{name: "Wheeling Jesuit University"},
{name: "Alternative Careers in Teaching (ACT!) WI"},
{name: "Alternative Route to Technology Educator Licensure - WI"},
{name: "Alverno College"},
{name: "Beloit College"},
{name: "Cardinal Stritch University"},
{name: "Carroll University"},
{name: "Carthage College"},
{name: "College of Menominee Nation"},
{name: "Concordia University Wisconsin"},
{name: "Cooperative Educational Service Agency 1: Proficiency Based Licensure Program"},
{name: "Cooperative Educational Service Agency 6: Residency in Teacher Education"},
{name: "Cooperative Educational Service Agency 7: Teacher Development Center"},
{name: "Edgewood College"},
{name: "eduCATE-WI"},
{name: "Lakeland College"},
{name: "Lawrence University"},
{name: "Maranatha Baptist University"},
{name: "Marian University"},
{name: "Marquette University"},
{name: "Mount Mary University"},
{name: "MTEC: Milwaukee Teacher Education Center"},
{name: "Northland College"},
{name: "Ripon College"},
{name: "Silver Lake College"},
{name: "St. Norbert College"},
{name: "University of Wisconsin-Eau Claire"},
{name: "University of Wisconsin-Green Bay"},
{name: "University of Wisconsin-La Crosse"},
{name: "University of Wisconsin-Madison"},
{name: "University of Wisconsin-Milwaukee"},
{name: "University of Wisconsin-Oshkosh"},
{name: "University of Wisconsin-Parkside"},
{name: "University of Wisconsin-Platteville"},
{name: "University of Wisconsin-River Falls"},
{name: "University of Wisconsin-Stevens Point"},
{name: "University of Wisconsin-Stout"},
{name: "University of Wisconsin-Superior"},
{name: "University of Wisconsin-Whitewater"},
{name: "Urban Education Fellows Program - WI"},
{name: "Viterbo University"},
{name: "Wisconsin Lutheran College"},
{name: "University of Wyoming"},
{name: "Teach for America - Los Angeles"},
{name: "Teach Western Mass"}
