{name: 'All Elementary Subjects'},
{name: 'Accounting'},
{name: 'Adapted P.E.'},
{name: 'Adaptive P.E.'},
{name: 'Aerobics'},
{name: 'Algebra'},
{name: 'Algebra I'},
{name: 'Algebra II'},
{name: 'American Literature'},
{name: 'Ancient Civilizations'},
{name: 'Ancient History'},
{name: 'Ancient Literature'},
{name: 'Animal Science'},
{name: 'Anthropology'},
{name: 'Applied Arts'},
{name: 'Arabic'},
{name: 'Archery'},
{name: 'Art'},
{name: 'Art Appreciation'},
{name: 'Art History'},
{name: 'Astronomy'},
{name: 'Auto Mechanics'},
{name: 'Band'},
{name: 'Basic First Aid and Safety'},
{name: 'Basic Math'},
{name: 'Basic Yard Care'},
{name: 'Biology'},
{name: 'Botany'},
{name: 'Bowling'},
{name: 'British Literature'},
{name: 'Business Math'},
{name: 'Business Technology'},
{name: 'Calculus'},
{name: 'Career Planning'},
{name: 'Ceramics'},
{name: 'Cheer'},
{name: 'Chemistry'},
{name: 'Child Development'},
{name: 'Chinese'},
{name: 'Choir'},
{name: 'Civics'},
{name: 'Classical literature'},
{name: 'Classical Music Studies'},
{name: 'Common Core'},
{name: 'Composition'},
{name: 'Computer Aided Design'},
{name: 'Computer Aided Drafting'},
{name: 'Computer Applications'},
{name: 'Computer Graphics'},
{name: 'Computer Repair'},
{name: 'Computer Science'},
{name: 'Computers'},
{name: 'Consumer Math'},
{name: 'Conversational Language'},
{name: 'Creative Writing'},
{name: 'Critical Thinking'},
{name: 'Culinary Arts'},
{name: 'Cycling'},
{name: 'Dance'},
{name: 'Debate'},
{name: 'Desktop Publishing'},
{name: 'Digital Arts'},
{name: 'Digital Media'},
{name: 'Drafting'},
{name: 'Drama'},
{name: 'Dramatics'},
{name: 'Drawing'},
{name: 'Drill Team'},
{name: 'Driver’s Education'},
{name: 'Earth Science'},
{name: 'Ecology'},
{name: 'Economics'},
{name: 'English'},
{name: 'Environmental Science'},
{name: 'Equestrian Skills'},
{name: 'Equine Science'},
{name: 'ESL – English as second language'},
{name: 'Fencing'},
{name: 'Figure skating'},
{name: 'Film as Literature'},
{name: 'Film Production'},
{name: 'Financial Management'},
{name: 'Fine Arts'},
{name: 'Flag'},
{name: 'Food Science'},
{name: 'Foreign Language'},
{name: 'Forensic Science'},
{name: 'French'},
{name: 'Fundamental Math'},
{name: 'Gardening'},
{name: 'Genealogy'},
{name: 'General Science'},
{name: 'Geography'},
{name: 'Geology'},
{name: 'Geometry'},
{name: 'German'},
{name: 'Golf'},
{name: 'Government'},
{name: 'Grammar'},
{name: 'Greek'},
{name: 'Greek and Roman History'},
{name: 'Gymnastics'},
{name: 'Handwork or handcrafts'},
{name: 'Handwriting'},
{name: 'Health'},
{name: 'Healthful Living {Personal Health}'},
{name: 'Hebrew'},
{name: 'Heroes, Myth and Legend'},
{name: 'High school guidance'},
{name: 'Hiking'},
{name: 'History'},
{name: 'History of Film'},
{name: 'History of Language'},
{name: 'Home Economics'},
{name: 'Home Management'},
{name: 'Home Organization'},
{name: 'Honors Courses'},
{name: 'Ice Skating'},
{name: 'Improvisational Theater'},
{name: 'Instrumental Music'},
{name: 'Intermediate Algebra'},
{name: 'Introduction to Algebra'},
{name: 'Japanese'},
{name: 'Journalism'},
{name: 'Keyboarding'},
{name: 'Language Arts'},
{name: 'Language Culture'},
{name: 'Language in Literature'},
{name: 'Latin'},
{name: 'Leadership'},
{name: 'Leather Working'},
{name: 'Life Lab or gardening'},
{name: 'Life Science'},
{name: 'Life Skills'},
{name: 'Logic'},
{name: 'Marine Biology'},
{name: 'Martial Arts'},
{name: 'Math'},
{name: 'Mathematics'},
{name: 'Medieval and Renaissance'},
{name: 'Medieval History'},
{name: 'Medieval Literature'},
{name: 'Metal Shop'},
{name: 'Metal Work'},
{name: 'Meteorology'},
{name: 'Middle School'},
{name: 'Middle School Guidance'},
{name: 'Modern Literature'},
{name: 'Modern US History'},
{name: 'Modern World History'},
{name: 'Movement or Eurythmy'},
{name: 'Music'},
{name: 'Music Appreciation'},
{name: 'Music Fundamentals'},
{name: 'Music History'},
{name: 'Music Theory'},
{name: 'Nutrition'},
{name: 'Occupational Therapy'},
{name: 'Oceanography'},
{name: 'Orchestra'},
{name: 'Organic Chemistry'},
{name: 'Outdoor Survival Skills'},
{name: 'Pageantry'},
{name: 'Painting'},
{name: 'Performing Arts'},
{name: 'Personal Finance and Investing'},
{name: 'Personal Organization'},
{name: 'Philosophy'},
{name: 'Photography'},
{name: 'Photojournalism'},
{name: 'Photoshop'},
{name: 'Physical Education'},
{name: 'Physical Education (P.E.)'},
{name: 'Physical Fitness'},
{name: 'Physical Science'},
{name: 'Physics'},
{name: 'Poetry'},
{name: 'Political Science'},
{name: 'Pottery'},
{name: 'Pre-Algebra'},
{name: 'Precalculus'},
{name: 'Programming'},
{name: 'Psychology'},
{name: 'Publishing Skills'},
{name: 'Reading'},
{name: 'Remedial English'},
{name: 'Remedial Math'},
{name: 'Renaissance History with US History'},
{name: 'Renaissance Literature'},
{name: 'Research Skills'},
{name: 'Rhetoric'},
{name: 'Rock Climbing'},
{name: 'SAT Prep'},
{name: 'School Counselor'},
{name: 'Science'},
{name: 'Sculpture'},
{name: 'Shakespeare'},
{name: 'Short Story'},
{name: 'Sign Language'},
{name: 'Small Engine Mechanics'},
{name: 'Social Sciences'},
{name: 'Social Skills'},
{name: 'Social Studies'},
{name: 'Sociology'},
{name: 'Spanish'},
{name: 'Special Education'},
{name: 'Special Education Day Class'},
{name: 'Specialized Certifications'},
{name: 'Speech'},
{name: 'Speech and Debate'},
{name: 'Speech Therapy'},
{name: 'Sports'},
{name: 'Statistics'},
{name: 'Study Skills'},
{name: 'Teaching AP'},
{name: 'Team Sports'},
{name: 'Theatre Arts'},
{name: 'Track and Field'},
{name: 'Trigonometry'},
{name: 'U.S. History and Government'},
{name: 'US History'},
{name: 'Veterinary Science'},
{name: 'Videography'},
{name: 'Vocabulary'},
{name: 'Voice'},
{name: 'Web Design'},
{name: 'Weightlifting'},
{name: 'Woodshop'},
{name: 'Word Processing'},
{name: 'Work-Study'},
{name: 'World Current Events (Global Issues)'},
{name: 'World Geography'},
{name: 'World History'},
{name: 'World Literature'},
{name: 'World Religions'},
{name: 'Yearbook'},
{name: 'Yoga'},
{name: 'Zoology'}
